Add Prettier - Closes #1403
LiskHQ/lisk-mobile pull request #1476
Opened 2022-09-09 11:00 UTC by ClementeSerrano

### What was the problem?
This PR resolves #1403

### How was it solved?
- [x] Add prettier configs and deps.
- [x] Prettify all project
- [x] Integrate prettier with eslint (solve any conflicts)
- [x] Integrate prettier with husky

### How was it tested?
Locally.

2022-09-09 14:49 UTC, ikem-legend approved these changes

2022-09-09 17:57 UTC, soroushm requested changes

2022-09-12 08:56 UTC, ClementeSerrano commented on .prettierrc
> +  "semi": false,
done

2022-09-13 06:43 UTC, ManuGowda commented on package.json
> +    "pretty-quick": "^3.1.3",
@ClementeSerrano I am bit confused why we are using `prettier-eslint", "pretty-quick"` aren't we suppose to just use `prettier`? how is it any different from any project configuration that we have e.g core https://github.com/LiskHQ/lisk-core/blob/development/package.json

you can cross check other sdk projects as well.

2022-09-13 09:40 UTC, ClementeSerrano commented on package.json
> +    "pretty-quick": "^3.1.3",
Removed `prettier-eslint` (I used it to solve some rules conflicts between prettier and eslint, but since they are solved, not longer required)

For `prettier-quick`, is a useful tool for making pre-commit hooks run prettier. But I researched a bit and finally went for `lint-staged`

2022-09-13 09:43 UTC, ClementeSerrano commented on .husky/pre-commit
>  . "$(dirname "$0")/_/husky.sh"
Basically, for some reason the husky setup from the `package.json` didn't work. Was only the other way. Actually, when running `husky init` , the husky folder is created

2022-09-13 09:43 UTC, ClementeSerrano commented on .husky/pre-commit
>  . "$(dirname "$0")/_/husky.sh"
Also, most guidelines recomment doing it this way (is an automatic file generation). Why do you like more the other way?

2022-09-13 10:09 UTC, ManuGowda commented on package.json
> +    "pretty-quick": "^3.1.3",
:) cool, thanks for addressing the comment.

2022-09-13 10:10 UTC, ManuGowda approved these changes

2022-09-13 14:25 UTC, merged

2022-09-14 10:09 UTC, soroushm commented on package.json
> +    "pretty-quick": "^3.1.3",
@ClementeSerrano @ManuGowda prettier-quick is for the husky its run prettier before commit and make sure the code it has right style could we have it in the project? other wise we aren't sure every one run prettier on their own