Adapt useCalculationFees hook business logic with new transaction structure - Closes #1502
LiskHQ/lisk-mobile pull request #1508
Opened 2022-10-07 13:01 UTC by ClementeSerrano

### What was the problem?

This PR resolves #1502

### How was it solved?

- [ ] Take from reference the current implementation of fees calculation in Mobile.
- [ ] Create and adapt the current methods from the `Transaction` class to cover all fees calculations use cases.
- [ ] Adopt transaction amount validation based on fee and balance availability
- [ ] Refactor and remove old fees calculations code (business logic and integration with UI).
- [ ] Integrate this new business logic with existing UI (input and output components).
- [ ] Adopt unit test 

### How was it tested?

Locally on iOS & Android Simulators

2022-10-07 15:12 UTC, soroushm requested changes

2022-10-07 15:12 UTC, soroushm commented on src/modules/SendToken/components/SummaryStep/hooks.js
> +  const transactionFee = Lisk.transactions.convertBeddowsToLSK(
its need to be memoized

2022-10-10 12:39 UTC, ClementeSerrano commented on src/modules/Transactions/utils/Transaction.js
>    computeFee() {
took https://github.com/LiskHQ/discussions/discussions/66 as ref

2022-10-11 13:07 UTC, soroushm commented on src/modules/SendToken/components/SummaryStep/hooks.js
> +  const transactionFee = Lisk.transactions.convertBeddowsToLSK(
its a computation running by every single re-render while user typing its going to be calculate again

2022-10-11 13:13 UTC, soroushm commented on src/modules/SendToken/constants/transactions.js
>    [moduleCommandNameIdMap.registerMultisignatureGroup]: {
as mobile dosnt have transaction other than transfer do we need to keep other command or schemas on it ?

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/hooks/useCCMFeeCalculator.js
> +      const fee = 0;
add ccm fees to the config then we can modify it later

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/hooks/useCCMFeeCalculator.js
> +      const fee = 0;
it dosnt need state 
```
export default function useCCMFeeCalculator({
  senderApplicationChainID,
  recipientApplicationChainID,
}) {
const isCCM = senderApplicationChainID !== recipientApplicationChainID
return  isCCM ? config.CCMFee : 0
}
```

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/hooks/useInitializationFeeCalculator.js
> +// TODO: Implement real calculation business logic.
create a ticket or like ccm fee added to the config you can find it has initialized fee by calling the transaction endpoint with the adress if has transaction the fee is 0 other wise its need to return fee from config

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/hooks/useTransactionPriorities.js
> -import { useGetFeesByPriorityQuery } from '../api/useGetFeesByPriorityQuery';
whats happend to the Priority?

2022-10-11 13:33 UTC, soroushm commented on src/modules/Transactions/utils/Transaction.js
> +    priority: null,
priority needs to be update after selection

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/components/SelectTokenStep/components.js
> +    Object.entries(transaction.data._feeEstimatePerByte).map(([code, fee]) => ({ code, fee }));
_feeEstimatePerByte is root element of transaction i dont think its in the data
transaction.data._feeEstimatePerByte

2022-10-11 13:33 UTC, soroushm commented on src/modules/Transactions/utils/Transaction.js
> +    this._feeEstimatePerByte = feeEstimatePerByte;
`this._` means is private and its not exposed, but some of the utils use it from outside pleas remove the underscore

2022-10-11 13:33 UTC, soroushm commented on src/modules/SendToken/components/SelectTokenStep/components.js
> +    Object.entries(transaction.data._feeEstimatePerByte).map(([code, fee]) => ({ code, fee }));
its better to use the query hooks directly here other than take it from private resource from transaction object

2022-10-11 15:20 UTC, ClementeSerrano commented on src/modules/SendToken/constants/transactions.js
>    [moduleCommandNameIdMap.registerMultisignatureGroup]: {
yes, but this hash table is for rendering the transaction information when is already submitted, not for creating them (all of them except token transfer), so we need it on the components

2022-10-12 14:03 UTC, ClementeSerrano commented on src/modules/SendToken/hooks/useCCMFeeCalculator.js
> +      const fee = 0;
done

2022-10-12 14:19 UTC, ClementeSerrano commented on src/modules/SendToken/components/SelectTokenStep/components.js
> +    Object.entries(transaction.data._feeEstimatePerByte).map(([code, fee]) => ({ code, fee }));
done

2022-10-12 14:19 UTC, ClementeSerrano commented on src/modules/Transactions/utils/Transaction.js
> +    this._feeEstimatePerByte = feeEstimatePerByte;
done

2022-10-12 14:19 UTC, ClementeSerrano commented on src/modules/Transactions/utils/Transaction.js
> +    priority: null,
its being updated

2022-10-13 12:28 UTC, ClementeSerrano commented on src/modules/SendToken/hooks/useInitializationFeeCalculator.js
> +// TODO: Implement real calculation business logic.
done

2022-10-13 13:05 UTC, soroushm approved these changes

2022-10-13 13:08 UTC, merged