Update Lisk Client to latest version (6.0.0-alpha.7)
LiskHQ/lisk-mobile pull request #1572
Opened 2022-12-29 14:52 UTC by ClementeSerrano

### What was the problem?

This PR resolves #1569

### How was it solved?

- [x] Bump lisk-client to 6.0.0-alpha.7
- [ ] Fix sign transaction missing `accountInitializationFee` field
- [ ] WIP

### How was it tested?

- [x] iOS Simulator
- [ ] Android Simulator

2023-01-03 15:03 UTC, ManuGowda requested changes

2023-01-03 15:03 UTC, ManuGowda commented on src/modules/Transactions/api/useDryRunTransactionMutation.js
> +          DropDownHolder.error('Failed transaction', data.errorMessage);
in case if result === 0, it will be a failed transaction but the errorMessage wont be there. We have to read the events to know what exactly failed. Read more [here](https://github.com/LiskHQ/discussions/discussions/72#discussioncomment-4580365).


For now as a workaround we can do this https://github.com/LiskHQ/lisk-desktop/pull/4696/files#diff-c942186c9c3d712c71e27a9f82eaaa99922cc9dfef7c1f9aa91afe1e09f5439dR185

but this is not the solution, I will discuss with research and sdk team to get a better solution for this.

2023-01-03 15:03 UTC, ManuGowda commented on src/modules/Transactions/utils/Transaction.js
> +    const numberOfEmptySignatures = this._auth.mandatoryKeys.length
sorry for giving you this code, since mobile only supports non multisignature accounts, we can consider this value as `0`.

2023-01-03 15:06 UTC, ClementeSerrano commented on package.json
> +    "buffer": "^4.9.1",
is not back. Was moved from place automatically by `yarn`

2023-01-03 15:06 UTC, ClementeSerrano commented on package.json
> -    "buffer": "^4.9.1",
here it was originally @Balanced02

2023-01-03 16:11 UTC, ClementeSerrano commented on src/modules/Transactions/api/useDryRunTransactionMutation.js
> +          DropDownHolder.error('Failed transaction', data.errorMessage);
ok, added. Marked also a TODO

2023-01-03 16:13 UTC, ClementeSerrano commented on src/modules/Transactions/utils/Transaction.js
> +    const numberOfEmptySignatures = this._auth.mandatoryKeys.length
done

2023-01-04 11:21 UTC, ManuGowda approved these changes

2023-01-04 11:21 UTC, ManuGowda commented on src/modules/Transactions/api/useDryRunTransactionMutation.js
> +      const errorMessage = mutation.data.data.events.map((e) => e.name).join(', ');
Please create an issue to handle the failed transaction and add todo here.

2023-01-04 11:38 UTC, ClementeSerrano commented on src/modules/Transactions/api/useDryRunTransactionMutation.js
> +      const errorMessage = mutation.data.data.events.map((e) => e.name).join(', ');
done: https://github.com/LiskHQ/lisk-mobile/issues/1578

2023-01-04 11:42 UTC, merged