Remove lisk-service support and adapt to migration
LiskHQ/lisk-mobile pull request #2178
Opened 2024-12-04 13:13 UTC by clemente-xyz

### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

### How was it tested?

2024-12-12 15:44 UTC, ikem-legend commented on src/modules/BlockchainApplication/context/ApplicationsContext.js
> +  console.log({ currentApplication: JSON.stringify(currentApplication) });
Please remove `console.log`.

2024-12-17 14:23 UTC, ikem-legend commented on src/modules/BlockchainApplication/context/ApplicationsContext.js
> +          data: LISK_TESTNET_APPLICATION,
Since there's no network switch, isn't the current application meant to be mainnet?

2024-12-18 11:36 UTC, ikem-legend commented on src/modules/Accounts/components/AccountList/index.js
> +          No accounts saved on this device.
I believe there should be translation here.

2024-12-18 11:38 UTC, ikem-legend commented on src/modules/Accounts/components/MigrateToL2Card/MigrateToL2Card.js
> +          continue using Lisk, migrate your accounts seamlessly on the Lisk Portal.
Translation not implemented here.

2024-12-18 11:42 UTC, ikem-legend commented on src/notifications/NotificationsService.js
> +        channelDescription: 'Channel for Lisk mobile notifications',
Translation not implemented here.

2024-12-18 11:42 UTC, ikem-legend commented on src/notifications/NotificationsService.js
> +        message: 'Migrate your Lisk accounts to the new L2 network on Lisk Portal.',
Translation not implemented here.

2024-12-27 12:02 UTC, clemente-xyz commented on src/modules/Accounts/components/AccountList/index.js
> +          No accounts saved on this device.
man i think doesnt matter. We are putting the app down and need to be fast with this

2024-12-27 12:02 UTC, clemente-xyz commented on src/modules/Accounts/components/MigrateToL2Card/MigrateToL2Card.js
> +          continue using Lisk, migrate your accounts seamlessly on the Lisk Portal.
same

2025-01-06 13:43 UTC, ikem-legend approved these changes

2025-01-06 14:39 UTC, ikem-legend commented on src/modules/Accounts/components/AccountCard/AccountCard.js
> +  const balance = fromBeddowsToLsk(legacyAccount?.token?.availableBalance || 0);
Balance should be the sum of available and locked balances.

2025-01-07 16:53 UTC, shuse2 commented on src/modules/Accounts/components/AccountCard/AccountCard.js
> +  const balance = fromBeddowsToLsk(legacyAccount?.token?.availableBalance || 0);
Available balance is string while on the right hand it's number `0`.
also, in this case it could be `?? 0`

2025-01-07 16:55 UTC, shuse2 commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
```suggestion
      maintainer: 'Lisk Limited',
```

2025-01-07 16:55 UTC, shuse2 commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
```suggestion
      maintainer: 'Lisk Limited',
```

2025-01-07 16:55 UTC, shuse2 commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
```suggestion
      maintainer: 'Lisk Limited',
```

2025-01-07 16:55 UTC, shuse2 commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
```suggestion
      maintainer: 'Lisk Limited',
```

2025-01-08 10:56 UTC, clemente-xyz commented on src/modules/Accounts/components/AccountCard/AccountCard.js
> +  const balance = fromBeddowsToLsk(legacyAccount?.token?.availableBalance || 0);
done

2025-01-08 10:58 UTC, clemente-xyz commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
done

2025-01-08 10:58 UTC, clemente-xyz commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
done

2025-01-08 10:58 UTC, clemente-xyz commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
done

2025-01-08 10:58 UTC, clemente-xyz commented on src/modules/BlockchainApplication/context/ApplicationsContext.constants.js
> +      maintainer: 'Lightcurve GmbH',
done

2025-01-09 11:54 UTC, ikem-legend commented on src/notifications/NotificationsService.js
> +        console.log(`Channel created: ${created}`);
Do we still need this console log?

2025-01-09 11:55 UTC, ikem-legend commented on src/notifications/NotificationsService.js
> +            console.log('Channel exists:', exists);
Same as above.

2025-01-09 11:55 UTC, ikem-legend commented on src/notifications/NotificationsService.js
> +        console.log('Notifications already scheduled');
Same here.

2025-01-09 12:06 UTC, clemente-xyz commented on src/notifications/NotificationsService.js
> +            console.log('Channel exists:', exists);
done

2025-01-09 12:06 UTC, clemente-xyz commented on src/notifications/NotificationsService.js
> +        console.log(`Channel created: ${created}`);
done

2025-01-09 12:57 UTC, shuse2 requested changes

2025-01-09 12:57 UTC, shuse2 commented on src/modules/Accounts/components/AccountCard/AccountCard.js
> +  const lockedBalance = legacyAccount?.token?.lockedBalance ?? 0;
this should be available balance and it is 
```suggestion
  const availableBalance = BigInt(legacyAccount?.token?.availableBalance ?? '0');
```

2025-01-09 12:57 UTC, shuse2 commented on src/modules/Accounts/components/AccountCard/AccountCard.js
> +    legacyAccount?.token?.lockedBalances.reduce((acc, curr) => acc + Number(curr.amount), 0) ?? 0;
this is lockedBalance (not available balance).
also, to be safe it should use the bigint
```suggestion
  const lockedBalance =
    legacyAccount?.token?.lockedBalances.reduce((acc, curr) => acc + BigInt(curr.amount), BigInt(0)) ?? BigInt(0);
```

2025-01-10 11:56 UTC, ikem-legend approved these changes

2025-01-10 13:41 UTC, shuse2 approved these changes

2025-01-10 13:41 UTC, merged